### PR TITLE
Target correct attribute for token

### PR DESCRIPTION
**Pull request by HosfordDotMe**
## Description:

Checks for the correct attribute to fix issue with new authorizations

**Related issue (if applicable):** fixes #<home-assistant issue number goes here>

**Pull request with documentation for [home-assistant.io](https://github.com/home-assistant/home-assistant.io) (if applicable):** home-assistant/home-assistant.io#<home-assistant.io PR number goes here>

## Example entry for `configuration.yaml` (if applicable):
```yaml

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Local tests pass with `tox`. **Your PR cannot be merged unless tests pass**
  - [X] There is no commented out code in this PR.
  - [X] I have followed the [development checklist][dev-checklist]

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [home-assistant.io](https://github.com/home-assistant/home-assistant.io)

If the code communicates with devices, web services, or third-party tools:
  - [ ] [_The manifest file_][manifest-docs] has all fields filled out correctly. Update and include derived files by running `python3 -m script.hassfest`.
  - [ ] New or updated dependencies have been added to `requirements_all.txt` by running `python3 -m script.gen_requirements_all`.
  - [ ] Untested files have been added to `.coveragerc`.

If the code does not interact with devices:
  - [ ] Tests have been added to verify that the new code works.

[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html
[manifest-docs]: https://developers.home-assistant.io/docs/en/creating_integration_manifest.html

### CODE REVIEW

**Comment by HosfordDotMe** [comment]
Had an issue seeing the token in the lyric object

**Comment by shellster** [comment]
> Had an issue seeing the token in the lyric object

I need to double check, but I'm pretty sure _token is exposed as token. If it isn't I need to submit another upstream patch to the python-lyric project because HomeAssistant won't allow merging of any code that references a private variable which is why I changed it in the first place.

**Comment by HosfordDotMe** [comment]
> > Had an issue seeing the token in the lyric object
> 
> I need to double check, but I'm pretty sure _token is exposed as token. If it isn't I need to submit another upstream patch to the python-lyric project because HomeAssistant won't allow merging of any code that references a private variable which is why I changed it in the first place.

It appears that the token is not returned with lyric.token in python-lyric. It might be because there is not a return in the token property and is not acting as a getter?

**Comment by HosfordDotMe** [comment]
https://repl.it/repls/ClearLoudCopyrightinfringement Shows the issue, so it appears that the change can be made upstream. I can make the request there.

**Comment by shellster** [comment]
Good catch.  Looks like an upstream patch is needed.  Appreciate your work.

-----Original Message-----

**Comment by shellster** [comment]
Looks like you are right.  We will need to submit an upstream patch.  Thanks for your hard work.  Gonna reject this PR and send a PR upstream

**Comment by shellster** [comment]
https://github.com/bramkragten/python-lyric/pull/6

**Pull request closed without merging**
